server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
